#
# Build image for fileserver.
#
FROM hkjn/golang

ENV CGO_ENABLED=0
WORKDIR /go/src/hkjn.me/fileserver/
COPY *.go ./
VOLUME ["/build"]
RUN go vet && \
    go build

CMD ["mv", "-v", "fileserver", "/build/"]

